sudo: required
server:
  - docker

before_install:
  - docker build -t jason/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jason/react-test npm test -- --coverage

after_success:
  - docker build -t jason/multi-client ./client
  - docker build -t jason/multi-server ./server
  - docker build -t jason/multi-nginx ./nginx
  - docker build -t jason/multi-worker ./worker
  # login docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push iamges to docker hub
  - docker push jason/multi-client
  - docker push jason/multi-server
  - docker push jason/multi-nginx
  - docker push jason/multi-worker
